version: "3.9"
services:
  weblication:
    build:
      context: .
      args:
        # Optional: andere Quelle für wSetup.zip
        WSETUP_URL: https://help-send.weblication.de/dev/downloads/wSetup.zip
    container_name: weblication20
    ports:
      - "8080:80"
    volumes:
      - ./webroot:/var/www/html
    environment:
      TZ: Europe/Berlin
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost/ || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
    restart: unless-stopped
